#sdk: "/Library/Ruby/Gems/1.8/gems/rhodes-3.2.3"
sdkversion: 3.2.1
name: Roster
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: com.rhomobile.roster
  BundleURLScheme: roster
wp:
  productid: b9259990-0cd4-012f-fce5-109add6cbe29
symbian:
  uid: 3836208245
android:
  version: 4.0
extensions:
  - json
  - another-extension
  - fileutils
  - mspec
capabilities:
  - camera
